### PR TITLE
Added `go test` & `goimports` actions

### LINKED ISSUE #5: Need automated testing via `go test`
Based on https://github.com/iver-wharf/iver-wharf.github.io/issues/75

Need to run Go tests and goimports formatting tests on commits and pull requests automatically.

As Wharf cannot do this yet, we should aim at using GitHub Actions.

Either we use the starter-workflow for Go https://github.com/actions/starter-workflows/blob/1d8891efc2151b2290b1d93e8489f9b1f41bd047/ci/go.yml which simply runs `go test`

Or we could look into a better integrated solution that could report failing tests as annotations inside the pull requests, such as:

- https://github.com/marketplace/actions/golang-test
- https://github.com/marketplace/actions/golang-test-annotations

### LINKED ISSUE #27: Feed build params from wharf-cmd-provisioner to wharf-cmd-worker pod
> Inspired by [RFC-0025: wharf-cmd provisioning](https://iver-wharf.github.io/rfcs/published/0025-wharf-cmd-provisioning)

> Depends on:
> - #10
> - #26

## Requirements

- From params given by wharf-api, supply them to the wharf-cmd-worker's CLI flags:
	- wharf-api: `ENVIRONMENT` => wharf-cmd-worker: `--environment ${ENVIRONMENT}`
	- wharf-api: `RUN_STAGES` => wharf-cmd-worker: `--stage ${RUN_STAGES}`
	- wharf-api: `VARS` => wharf-cmd-worker: `--input key=value` (used multiple times, one per value)

## Out of scope (don't focus on this yet)

Nothing comes to mind

### PR DESCRIPTION
**Pull request by jilleJr**
## Summary

- Added `go test` with annotations via https://github.com/marketplace/actions/golang-test-annotations
- Added `goimports` to `git diff` action

## Motivation

Based on iver-wharf/wharf-api#106

Closes #5

### CODE REVIEW

**Comment by jilleJr** [comment]
Oh the tests actually fail :o

Looks like some incorrect wharf-core logger usage.

I'm not going to tackle that in this PR though. They'll have to keep on failing in master, and get fixed in a different PR.

**Review by Alexamakans — APPROVED** [review]

**Comment by fredx30** [comment]
> Oh the tests actually fail :o
> 
> Looks like some incorrect wharf-core logger usage.
> 
> I'm not going to tackle that in this PR though. They'll have to keep on failing in master, and get fixed in a different PR.

Why merge now if it only results in failing tests? Would it be better to re-draft it fix the issue and then merge this. That way it would come as a benefit instead of a hinderance.

**Comment by jilleJr** [comment]
> Why merge now if it only results in failing tests? Would it be better to re-draft it fix the issue and then merge this. That way it would come as a benefit instead of a hinderance.

Because I don't want to spend time on this right now, and I want to forget about it. But I can mark it as draft and open an issue about it instead

**Review by fredx30 — APPROVED** [review]
Looks good - masterplan in https://github.com/iver-wharf/iver-wharf.github.io/issues/75

**Pull request merged**
